name: Pipeline de Qualidade e Testes

on:
  push:
    branches: [ "main" ]

jobs:
  testar_e_analisar_codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Preparar o ambiente PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none

    - name: Instalar dependencias do projeto (Composer)
      run: composer install --no-progress

    - name: 1. Executar Testes Unitarios (PHPUnit)
      run: php vendor/bin/phpunit tests/
      env:
        DB_HOST: banco_falso_ci
        SMTP_PASS: senha_falsa_ci
        SMTP_PORT: 587

    - name: 2. Analisar Estetica do Codigo (PHP CodeSniffer)
      run: hp vendor/bin/phpcs -n --standard=PSR12 cadastro_receita.php editar_receita.php

    - name: 3. Analisar Qualidade Logica (PHP Mess Detector)
      run: php vendor/bin/phpmd cadastro_receita.php,editar_receita.php text cleancode,codesize,naming